# Generated by Django 2.2 on 2021-06-15 07:21

from django.db import migrations, models
import django.db.models.deletion
import reviews.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(default='', max_length=20,
                 validators=[reviews.validators.validate_symbols])),
                ('address1', models.CharField(default='', max_length=10,
                 validators=[reviews.validators.validate_address1])),
                ('address2', models.CharField(default='', max_length=10,
                 validators=[reviews.validators.validate_address2])),
                ('address3', models.CharField(default='', max_length=10,
                 validators=[reviews.validators.validate_address3])),
                ('temp', models.CharField(default='', max_length=20,
                 validators=[reviews.validators.validate_symbols])),
            ],
        ),
        migrations.CreateModel(
            name='CrawlResult',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('final_rating', models.FloatField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('comment', models.CharField(default='', max_length=500)),
                ('date', models.DateField(null=True)),
                ('user_input_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='reviews.UserInput')),
            ],
        ),
    ]
