# Generated by Django 2.2 on 2021-06-10 05:07

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(default='', max_length=20, validators=[reviews.validators.validate_symbols])),
                ('address1', models.CharField(default='', max_length=10, validators=[reviews.validators.validate_address1])),
                ('address2', models.CharField(default='', max_length=10, validators=[reviews.validators.validate_address2])),
                ('address3', models.CharField(default='', max_length=10, validators=[reviews.validators.validate_address3])),
                ('r_kakao', models.CharField(default='', max_length=20)),
                ('r_naver', models.CharField(default='', max_length=20)),
                ('final_rating', models.FloatField()),
                ('rating', models.FloatField()),
                ('comment', models.CharField(default='', max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
