# Generated by Django 2.2 on 2021-05-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=50)),
                ('final_rating', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
