# Generated by Django 2.2 on 2021-06-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='final_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
