# Generated by Django 2.2 on 2021-06-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='final_rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='position',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.CharField(max_length=20),
        ),
    ]
