# Generated by Django 2.2 on 2021-06-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_crawlresult_userinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='restaurant',
            field=models.CharField(default='', max_length=20),
        ),
    ]
