# Generated by Django 2.2 on 2021-06-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210604_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='position',
            new_name='address',
        ),
        migrations.AddField(
            model_name='review',
            name='website',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
