# Generated by Django 2.2 on 2021-06-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210604_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='address',
            field=models.CharField(max_length=20),
        ),
    ]
