# Generated by Django 2.2 on 2021-06-09 06:40

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20210608_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='website',
        ),
        migrations.AddField(
            model_name='review',
            name='r_kakao',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='r_naver',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='address',
            field=models.CharField(max_length=20, validators=[reviews.validators.validate_address]),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.CharField(max_length=20, validators=[reviews.validators.validate_symbols]),
        ),
    ]
